CREATE TABLE `leases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`propertyId` int,
	`documentUrl` text,
	`documentKey` text,
	`tenantName` varchar(255),
	`tenantCategory` varchar(100),
	`leasableArea` decimal(10,2),
	`currentBaseRent` decimal(12,2),
	`rentCurrency` varchar(3) DEFAULT 'PLN',
	`rentSteps` json,
	`turnoverRentPercentage` decimal(5,2),
	`breakpointType` varchar(50),
	`breakpointValue` decimal(12,2),
	`reportingFrequency` varchar(50),
	`excludedSales` json,
	`indexationIndex` varchar(100),
	`indexationFrequency` varchar(50),
	`indexationBaseMonth` date,
	`indexationCap` decimal(5,2),
	`indexationFloor` decimal(5,2),
	`proRataShare` decimal(5,4),
	`serviceChargeCapType` varchar(50),
	`serviceChargeCapValue` decimal(12,2),
	`excludedCosts` json,
	`serviceChargeStatus` varchar(50) DEFAULT 'Pending',
	`leaseExpiryDate` date,
	`tenantBreakOptionDate` date,
	`tenantBreakNoticePeriod` int,
	`renewalDeadline` date,
	`hasNonStandardClause` int DEFAULT 0,
	`extractionStatus` varchar(20) DEFAULT 'pending',
	`dataCompletenessScore` decimal(5,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leases_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `properties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`location` varchar(255),
	`totalGLA` decimal(12,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `properties_id` PRIMARY KEY(`id`)
);
